// Autogenerated from Pigeon (v3.2.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class FLTZnaidyAnnotation;
@class FLTZnaidyAnnotationOptions;

@interface FLTZnaidyAnnotation : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithId:(NSString *)id
    geometry:(nullable NSDictionary<NSString *, id> *)geometry;
@property(nonatomic, copy) NSString * id;
@property(nonatomic, strong, nullable) NSDictionary<NSString *, id> * geometry;
@end

@interface FLTZnaidyAnnotationOptions : NSObject
+ (instancetype)makeWithGeometry:(nullable NSDictionary<NSString *, id> *)geometry;
@property(nonatomic, strong, nullable) NSDictionary<NSString *, id> * geometry;
@end

/// The codec used by FLTOnZnaidyAnnotationClickListener.
NSObject<FlutterMessageCodec> *FLTOnZnaidyAnnotationClickListenerGetCodec(void);

@interface FLTOnZnaidyAnnotationClickListener : NSObject
- (instancetype)initWithBinaryMessenger:(id<FlutterBinaryMessenger>)binaryMessenger;
- (void)onZnaidyAnnotationClickAnnotation:(FLTZnaidyAnnotation *)annotation completion:(void(^)(NSError *_Nullable))completion;
@end
/// The codec used by FLT_ZnaidyAnnotationMessager.
NSObject<FlutterMessageCodec> *FLT_ZnaidyAnnotationMessagerGetCodec(void);

@protocol FLT_ZnaidyAnnotationMessager
- (void)createManagerId:(NSString *)managerId annotationOptions:(FLTZnaidyAnnotationOptions *)annotationOptions completion:(void(^)(FLTZnaidyAnnotation *_Nullable, FlutterError *_Nullable))completion;
- (void)updateManagerId:(NSString *)managerId annotation:(FLTZnaidyAnnotation *)annotation completion:(void(^)(FlutterError *_Nullable))completion;
- (void)deleteManagetId:(NSString *)managetId annotation:(FLTZnaidyAnnotation *)annotation completion:(void(^)(FlutterError *_Nullable))completion;
@end

extern void FLT_ZnaidyAnnotationMessagerSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLT_ZnaidyAnnotationMessager> *_Nullable api);

NS_ASSUME_NONNULL_END
